### ISSUE TITLE
whisper flag consoleio is not working

### ISSUE THREAD

**Issue by predator-111** [tenstorrent/whisper#2]
I'm having trouble using the consoleio flag with the latest commit after the addition of Args.cpp. Previously, it worked fine with commit 4fb1630c177016aa24835819839d2323d255e0cb (April 4, 2024), where the default ISA was changed to imacfd for RISCOF tests.
Could you please let me know if there are any additional changes I need to make in order to get it working again? Any guidance would be greatly appreciated. Thank you for your help!

**Comment by jrahmeh** [comment]
Please describe the failure?  What happens when you use consoleio?  Please provide the command line you used and if possible the test you were running.

**Comment by jrahmeh** [comment]
The console IO functionality got dropped by accident.  It should now be restored.

**Comment by predator-111** [comment]
build-Linux/whisper --consoleio <uart_address> --configfile ./whisper.json --noconinput <elf_name> --logfile whisper.log
Command working fine on April 4 commit. On later commits it is not able to print anything by using the same command.

**Comment by jrahmeh** [comment]
I updated the code 3 days ago to fix the issue. Is it still failing for you?

**Comment by predator-111** [comment]
Thanks @jrahmeh. It is working now.
